# Generated by Django 5.1.7 on 2026-10-09 17:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('trader_type', models.CharField(choices=[('LEGAL', 'Legal Trader'), ('INFORMAL', 'Informal Trader')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('NEEDS_CORRECTION', 'Needs Correction'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='SUBMITTED', max_length=30)),
                ('name', models.CharField(help_text='Trade Name or Trader Full Name', max_length=255)),
                ('owner_full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('specific_location', models.CharField(blank=True, max_length=255)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('correction_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_traders', to=settings.AUTH_USER_MODEL)),
                ('kebele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traders', to='locations.kebele')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_traders', to=settings.AUTH_USER_MODEL)),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traders', to='locations.woreda')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(db_index=True, max_length=50, unique=True)),
                ('trade_registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('age', models.PositiveIntegerField(default=30)),
                ('business_sector', models.CharField(choices=[('GENERAL_TRADE', 'General Trade'), ('RETAIL_WHOLESALE_GOODS', 'Retail & Wholesale Goods'), ('AGRICULTURE_AGRO_PROCESSING', 'Agriculture & Agro Processing'), ('MANUFACTURING_PRODUCTION', 'Manufacturing & Production'), ('SERVICE_PROVIDER', 'Service Provider'), ('OTHER', 'Other')], default='GENERAL_TRADE', max_length=50)),
                ('trade_scale', models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], default='RETAIL', max_length=20)),
                ('business_ownership_type', models.CharField(choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('PLC', 'Private Limited Company (PLC)'), ('PARTNERSHIP', 'Partnership'), ('ASSOCIATION_COOPERATIVE', 'Association / Cooperative')], default='SOLE_PROPRIETORSHIP', max_length=50)),
                ('issuing_institution', models.CharField(default='Harari Region Trade and Industry Development Bureau', max_length=255)),
                ('date_of_issuance', models.DateField()),
                ('house_number_plot_id', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('officer_signature', models.CharField(blank=True, max_length=100)),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_details', to='traders.trader')),
            ],
        ),
        migrations.CreateModel(
            name='InformalTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_resident_id', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('age', models.PositiveIntegerField(default=28)),
                ('specific_location_market_area', models.CharField(max_length=255)),
                ('nature_of_trade_activity', models.CharField(choices=[('STREET_VENDING_OPEN_MARKET', 'Street Vending & Open Market'), ('PETTY_RETAIL', 'Petty Retail'), ('HANDCRAFT_INFORMAL_PRODUCTION', 'Handcraft & Informal Production'), ('OTHER', 'Other')], default='STREET_VENDING_OPEN_MARKET', max_length=50)),
                ('estimated_capital_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reason_for_operating_informally', models.CharField(choices=[('LACK_OF_CAPITAL', 'Lack of Working Capital'), ('COMPLEX_BUREAUCRACY', 'Complex Registration Bureaucracy'), ('TEMPORARY_SEASONAL_ACTIVITY', 'Temporary or Seasonal Trading Activity'), ('OTHER', 'Other')], default='LACK_OF_CAPITAL', max_length=50)),
                ('formalization_status_recommendation', models.CharField(choices=[('READY_FOR_TIN_MICRO_ENTERPRISE', 'Ready for TIN & Micro-Enterprise Transition'), ('NEEDS_AWARENESS_LEGAL_SUPPORT', 'Needs Awareness & Legal Advisory Support'), ('FOLLOW_UP_REQUIRED', 'Follow-up Field Inspection Required')], default='READY_FOR_TIN_MICRO_ENTERPRISE', max_length=50)),
                ('enumerator_data_collector_name', models.CharField(max_length=255)),
                ('date_of_assessment', models.DateField()),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informal_details', to='traders.trader')),
            ],
        ),
    ]
