# Generated by Django 5.2.18 on 2026-10-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('trader_type', models.CharField(choices=[('LEGAL', 'Legal Trader'), ('INFORMAL', 'Informal Trader')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('NEEDS_CORRECTION', 'Needs Correction'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='SUBMITTED', max_length=30)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('owner_full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('business_address', models.CharField(blank=True, max_length=255)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
                ('kebele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traders', to='locations.kebele')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_traders', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traders', to='locations.region')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_traders', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_traders', to=settings.AUTH_USER_MODEL)),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traders', to='locations.woreda')),
            ],
            options={
                'db_table': 'ht_traders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255)),
                ('owner_full_name', models.CharField(max_length=255)),
                ('tin', models.CharField(db_index=True, max_length=50)),
                ('trade_registration_number', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10)),
                ('age', models.PositiveIntegerField(default=30)),
                ('house_number_plot_id', models.CharField(blank=True, max_length=100)),
                ('business_sector', models.CharField(choices=[('GENERAL_TRADE', 'General Trade & Distribution'), ('RETAIL_WHOLESALE_GOODS', 'Retail & Wholesale Goods'), ('AGRICULTURE_AGRO_PROCESSING', 'Agriculture & Agro-Processing'), ('MANUFACTURING_PRODUCTION', 'Manufacturing & Light Production'), ('SERVICE_PROVIDER', 'Hotel, Tourism & Services'), ('OTHER', 'Other Commercial Sector')], default='GENERAL_TRADE', max_length=50)),
                ('trade_scale', models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], default='RETAIL', max_length=20)),
                ('business_ownership_type', models.CharField(choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('PLC', 'Private Limited Company (PLC)'), ('PARTNERSHIP', 'Partnership'), ('ASSOCIATION_COOPERATIVE', 'Cooperative / Association')], default='SOLE_PROPRIETORSHIP', max_length=50)),
                ('issuing_institution', models.CharField(default='Harari Trade & Industry Development Agency', max_length=255)),
                ('date_of_issuance', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('officer_signature', models.CharField(blank=True, max_length=255)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_details', to='traders.trader')),
            ],
            options={
                'db_table': 'ht_legal_traders',
            },
        ),
        migrations.CreateModel(
            name='InformalTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('age', models.PositiveIntegerField(default=25)),
                ('national_id_resident_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('specific_location_market_area', models.CharField(max_length=255)),
                ('nature_of_trade_activity', models.CharField(choices=[('STREET_VENDING_OPEN_MARKET', 'Street Vending & Open Market'), ('PETTY_RETAIL', 'Petty Retail / Kiosk / Corner Stand'), ('HANDCRAFT_INFORMAL_PRODUCTION', 'Handcraft & Informal Workshop'), ('OTHER', 'Other Informal Activity')], default='PETTY_RETAIL', max_length=50)),
                ('estimated_capital_assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('reason_for_operating_informally', models.CharField(choices=[('LACK_OF_CAPITAL', 'Lack of Initial Working Capital'), ('COMPLEX_BUREAUCRACY', 'Complex Registration Procedures'), ('TEMPORARY_SEASONAL_ACTIVITY', 'Temporary / Seasonal Activity'), ('OTHER', 'Other Livelihood Challenges')], default='LACK_OF_CAPITAL', max_length=50)),
                ('enumerator_data_collector_name', models.CharField(blank=True, max_length=255)),
                ('date_of_assessment', models.DateField()),
                ('formalization_status_recommendation', models.CharField(choices=[('READY_FOR_TIN_MICRO_ENTERPRISE', 'Ready for Formal TIN & Micro-Enterprise License'), ('NEEDS_AWARENESS_LEGAL_SUPPORT', 'Needs Financial Literacy & Legal Coaching'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required (Transition in Progress)')], default='READY_FOR_TIN_MICRO_ENTERPRISE', max_length=50)),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informal_details', to='traders.trader')),
            ],
            options={
                'db_table': 'ht_informal_traders',
            },
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['status', 'woreda'], name='ht_traders_status_92f321_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['trader_type', 'status'], name='ht_traders_trader__de48c6_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['created_at', 'status'], name='ht_traders_created_3f0407_idx'),
        ),
    ]
