# Generated by Django 5.2.18
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='assigned_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_trader_reviews',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='trader',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
