# Generated by Django 5.2.18 on 2026-10-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_ASSESSED', 'Not Assessed'), ('READY_FOR_FORMALIZATION', 'Ready for Formalization'), ('NEEDS_SUPPORT', 'Needs Support & Awareness'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required'), ('FORMALIZED', 'Formalized (Licensed)')], db_index=True, default='NOT_ASSESSED', max_length=50)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('readiness_assessment', models.TextField(blank=True)),
                ('barriers', models.TextField(blank=True)),
                ('recommended_support', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('support_provided', models.TextField(blank=True)),
                ('formalization_notes', models.TextField(blank=True)),
                ('formalized_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formalization_assessments', to=settings.AUTH_USER_MODEL)),
                ('responsible_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formalized_actions', to=settings.AUTH_USER_MODEL)),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formalization_record', to='traders.trader')),
            ],
            options={
                'db_table': 'ht_formalization_records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
