# Generated by Django 5.1.7 on 2026-10-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalizationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_ASSESSED', 'Not Assessed'), ('READY_FOR_FORMALIZATION', 'Ready for Formalization'), ('NEEDS_SUPPORT', 'Needs Support & Training'), ('FOLLOW_UP_REQUIRED', 'Follow-up Inspection Required'), ('FORMALIZED', 'Formalized to Legal Enterprise')], db_index=True, default='NOT_ASSESSED', max_length=40)),
                ('support_package', models.CharField(blank=True, help_text='Type of institutional assistance provided (e.g., Bookkeeping training, workspace allocation)', max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('formalized_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_formalization_assessments', to=settings.AUTH_USER_MODEL)),
                ('assigned_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_formalizations', to=settings.AUTH_USER_MODEL)),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formalization_assessment', to='traders.trader')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
