# Generated by Django 5.1.7 on 2026-10-09 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CLAIM', 'Claim for Review'), ('ASSIGN', 'Assigned'), ('START_REVIEW', 'Review Started'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('RETURN', 'Returned for Correction')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to='traders.trader')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
