# Generated by Django 5.1.7 on 2026-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REGISTER_TRADER', 'Register Trader'), ('UPDATE_TRADER', 'Update Trader'), ('SUBMIT_TRADER', 'Submit Trader'), ('CLAIM_REVIEW', 'Claim Review'), ('APPROVE_TRADER', 'Approve Trader'), ('RETURN_TRADER', 'Return Trader for Correction'), ('REJECT_TRADER', 'Reject Trader'), ('FORMALIZE_TRADER', 'Formalize Trader'), ('DELETE_TRADER', 'Delete Trader'), ('EXPORT_CSV', 'Export CSV Data'), ('EXPORT_EXCEL', 'Export Excel Data'), ('PRINT_CERTIFICATE', 'Print Certificate'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], db_index=True, max_length=50)),
                ('trader_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('details', models.TextField()),
                ('user', models.CharField(db_index=True, default='system', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
