# Generated by Django 5.2.18 on 2026-10-09 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('RECORD_CREATED', 'Record Created'), ('RECORD_UPDATED', 'Record Updated'), ('SUBMITTED', 'Submitted for Review'), ('RESUBMITTED', 'Resubmitted after Correction'), ('CLAIMED', 'Claimed for Review'), ('ASSIGNED', 'Assigned to Reviewer'), ('REVIEW_STARTED', 'Review Started'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('FORMALIZATION_ASSESSED', 'Formalization Assessed'), ('FORMALIZATION_UPDATED', 'Formalization Updated'), ('FORMALIZED', 'Trader Formalized'), ('ARCHIVED', 'Trader Archived'), ('EXPORT_CSV', 'Exported to CSV'), ('EXPORT_EXCEL', 'Exported to Excel'), ('EXPORT_PDF', 'Exported to PDF'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('LOCATION_CREATED', 'Location Created')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('previous_state', models.CharField(blank=True, max_length=50)),
                ('new_state', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ht_audit_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ht_audit_ev_entity__c37498_idx'), models.Index(fields=['action', 'timestamp'], name='ht_audit_ev_action_726677_idx')],
            },
        ),
    ]
