# Generated by Django 5.1.7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(
                choices=[
                    ('REGISTER_TRADER', 'Register Trader'),
                    ('UPDATE_TRADER', 'Update Trader'),
                    ('SUBMIT_TRADER', 'Submit Trader'),
                    ('CLAIM_REVIEW', 'Claim Review'),
                    ('APPROVE_TRADER', 'Approve Trader'),
                    ('RETURN_TRADER', 'Return Trader for Correction'),
                    ('REJECT_TRADER', 'Reject Trader'),
                    ('FORMALIZE_TRADER', 'Formalize Trader'),
                    ('DELETE_TRADER', 'Delete Trader'),
                    ('ARCHIVE_TRADER', 'Archive Trader'),
                    ('EXPORT_CSV', 'Export CSV Data'),
                    ('EXPORT_EXCEL', 'Export Excel Data'),
                    ('EXPORT_PDF', 'Export PDF Report'),
                    ('PRINT_CERTIFICATE', 'Print Certificate'),
                    ('LOGIN', 'User Login'),
                    ('LOGOUT', 'User Logout'),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
