# Generated by Django 6.1.2 on 2026-10-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Woreda',
                'verbose_name_plural': 'Woredas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kebele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kebeles', to='locations.woreda')),
            ],
            options={
                'verbose_name': 'Kebele',
                'verbose_name_plural': 'Kebeles',
                'ordering': ['woreda__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('woreda', 'name'), name='unique_kebele_name_per_woreda'), models.UniqueConstraint(fields=('woreda', 'code'), name='unique_kebele_code_per_woreda')],
            },
        ),
    ]
