# Generated by Django 5.2.18
import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_loginattempt'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.HTTMISUserManager()),
            ],
        ),
    ]
