# Generated by Django 6.1.2 on 2026-10-07 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('trader_type', models.CharField(choices=[('LEGAL', 'Legal Trader'), ('INFORMAL', 'Informal Trader')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_activity', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kebele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traders', to='locations.kebele')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_traders', to=settings.AUTH_USER_MODEL)),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traders', to='locations.woreda')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
