# Generated by Django 6.1.2 on 2026-10-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='business_activity',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='kebele',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='woreda',
        ),
        migrations.CreateModel(
            name='InformalTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('national_id_resident_id', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('specific_location_market_area', models.CharField(max_length=200)),
                ('nature_of_trade_activity', models.CharField(max_length=100)),
                ('estimated_capital_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason_for_operating_informally', models.CharField(max_length=100)),
                ('enumerator_data_collector_name', models.CharField(blank=True, max_length=200)),
                ('date_of_assessment', models.DateField()),
                ('formalization_status_recommendation', models.CharField(max_length=100)),
                ('kebele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informal_traders', to='locations.kebele')),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informal_details', to='traders.trader')),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informal_traders', to='locations.woreda')),
            ],
        ),
        migrations.CreateModel(
            name='LegalTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200)),
                ('owner_full_name', models.CharField(max_length=200)),
                ('tin', models.CharField(max_length=100, verbose_name='TIN')),
                ('trade_registration_number', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('house_number_plot_id', models.CharField(blank=True, max_length=100)),
                ('business_sector', models.CharField(max_length=100)),
                ('trade_scale', models.CharField(max_length=20)),
                ('business_ownership_type', models.CharField(max_length=50)),
                ('issuing_institution', models.CharField(max_length=200)),
                ('date_of_issuance', models.DateField()),
                ('data_entered_by', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('officer_signature', models.CharField(blank=True, max_length=200)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('kebele', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_traders', to='locations.kebele')),
                ('trader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_details', to='traders.trader')),
                ('woreda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_traders', to='locations.woreda')),
            ],
        ),
    ]
