# Generated by Django 6.1.2 on 2026-10-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0002_remove_trader_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaltrader',
            name='formalization_status_recommendation',
            field=models.CharField(choices=[('READY_FOR_TIN_MICRO_ENTERPRISE', 'Ready for TIN & Micro-Enterprise Registration'), ('NEEDS_AWARENESS_LEGAL_SUPPORT', 'Needs Awareness/Legal Support'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required')], max_length=100),
        ),
        migrations.AlterField(
            model_name='informaltrader',
            name='nature_of_trade_activity',
            field=models.CharField(choices=[('STREET_VENDING_OPEN_MARKET', 'Street Vending/Open Market'), ('PETTY_RETAIL', 'Petty Retail'), ('HANDCRAFT_INFORMAL_PRODUCTION', 'Handcraft/Informal Production'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='informaltrader',
            name='reason_for_operating_informally',
            field=models.CharField(choices=[('LACK_OF_CAPITAL', 'Lack of Capital'), ('COMPLEX_BUREAUCRACY', 'Complex Bureaucracy'), ('TEMPORARY_SEASONAL_ACTIVITY', 'Temporary/Seasonal Activity'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='legaltrader',
            name='business_ownership_type',
            field=models.CharField(choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('PLC', 'Private Limited Company (PLC)'), ('PARTNERSHIP', 'Partnership'), ('ASSOCIATION_COOPERATIVE', 'Association/Cooperative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='legaltrader',
            name='business_sector',
            field=models.CharField(choices=[('GENERAL_TRADE', 'General Trade'), ('RETAIL_WHOLESALE_GOODS', 'Retail/Wholesale Goods'), ('AGRICULTURE_AGRO_PROCESSING', 'Agriculture/Agro-processing'), ('MANUFACTURING_PRODUCTION', 'Manufacturing/Production'), ('SERVICE_PROVIDER', 'Service Provider'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='legaltrader',
            name='trade_scale',
            field=models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail')], max_length=20),
        ),
    ]
